from slugify import slugify_unicode

def slug(s):
    """
    Return the slug value of a string.
    """
    result = ""
    prev_hyph = True
    for c in s.lower():
        if c.isalpha() or c.isdigit():
                result += c
                prev_hyph = False
        else:
            if not prev_hyph:
                result += "-"
            prev_hyph = True
    if result and result[-1] == "-":
        result = result[:-1]
    return result

def f_slug(s):
    s = s.lower()
    s = "".join(c if (c.isalpha() or c.isdigit()) else "-" for c in s)
    s = "-".join(filter(bool, s.split("-")))
    return s

def u_slug(s):
    return slugify_unicode(s, to_lower=True)

TITLES = [
    "",
    "Global public health notes",
    "Linux tricks",
    "Having a personal website",
    "Content creation",
    "Computing",
    "Issa Rice",
    "Using Hakyll with GitHub Pages",
    "Two definitions for the least upper bound",
    "Setting up Jekyll on GitHub",
    "Quantified self",
    "Proving the limit laws",
    "pLaTeX",
    "Notes on variables",
    "Minimality exercise from Halmos",
    "Japanese input on the command line (framebuffer)",
    "“Elementary properties of closures”",
    "Burning CDs and DVDs on the command line",
    "Zip in Python",
    "Some thoughts on college education",
    "Colophon",
    "About this site",
    "Education",
    "Effective altruism",
    "Math",
    "Contact",
    "Fonts",
    "Friendship",
    "Making my working environment portable",
    "What is it like to attend the Seattle Japanese School?",
    "Music I like to listen to",
    "MATH 135",
    "Tag ontology",
    "Some epsilon-delta proofs",
    "Single source publishing",
    "Mathematics and notation",
    "MATH 336",
    "MATH 335",
    "MATH 334",
    "High school student: “Universities should pay me.”",
    "Font configuration",
    "FOL puzzle",
    "CSE 351",
    "CSE 311",
    "Betting odds",
    "Wikipedia",
    "University of Washington",
    "Information regarding website source and page source",
    "Good entry point",
    "Facebook",
    "Comments",
    "About",
    "Advice for young people",
    "CSE 473",
    "Installing Haskell",
    "Egoism of personal websites",
    "Material implication",
    "MATH 136",
    "Winter 2016 at the University of Washington",
    "CSE 332",
    "EconLog",
    "Spring 2015 at the University of Washington",
    "Notes on double-majoring in CSE and math at UW",
    "Vim",
    "Autumn 2015 at the University of Washington",
    "College computer setup",
    "AMATH 383",
    "Belief",
    "2channel",
    "Dual monitors",
    "Public choice",
    "Bee and I",
    "“Dear John”",
    "Self-help",
    "Git",
    "UW: year one in review",
    "wikiHow",
    "Identity",
    "Fishmans",
    "In praise of dullness",
    "Depression",
    "Sunhat",
    "Quora",
    "My Quora answers",
    "Effective altruism links",
    "Castration",
    "Androgyny",
    "Pederasty",
    "Archiving websites on Unix-like systems",
    "Anonymity",
    "Firefox",
    "God (disambiguation)",
    "Make-work bias",
    "Perfectionism",
    "Archiving Facebook",
    "Regular screenshots",
    "duplicity",
    "Attic",
    "Hiring and judging character",
    "Bash",
    "Linking effectively",
    "Long-term thinking",
    "Effective altruism and Asperger syndrome",
    "Resources for the University of Washington",
    "Pandoc",
    "Canonical naming",
    "Commenting on this site",
    "Personal thoughts on licensing",
    "Polyamory",
    "Unschooling",
    "Ōe Kenzaburō",
    "Profile",
    "Debian installation notes",
    "Using a tree structure for websites",
    "Selfish Reasons to Have More Kids",
    "Open Borders: The Case",
    "MATH 134",
    "Status",
    "The value of content creation",
    "Arguments for and against blogs",
    "Taking up ambitious open-ended side projects (as a high school/college student)",
    "Overlinking",
    "My UW essays",
    "CSE 143",
    "UW CSE Departmental Orientation",
    "Useful shell commands",
    "PHYS 121",
    "mp3splt",
    "mojix",
    "MediaWiki with nginx on Linode",
    "Linkability",
    "Julian Simon’s Good Mood",
    "How should I properly pronounce your name?",
    "ENGL 478",
    "CSS",
    "Between mid-June and late September, what is the best time to visit Tokyo?",
    "ATM S 559",
    "Feed",
    "Exercise",
    "Cognito Mentoring",
    "My UW honors portfolio",
    "Winter 2015 at the University of Washington",
    "Thoughts on using Reddit effectively",
    "Stalking",
    "rsync",
    "Requirements for a website",
    "Questions",
    "Personal review",
    "Open Borders from a cause prioritization viewpoint",
    "Not a dictionary",
    "Minimalism",
    "Male variance",
    "Longevity",
    "Long Content",
    "List of analogies",
    "LessWrong",
    "Jargon",
    "Internet security",
    "Individual transparency",
    "Importance of having differently-aged peers",
    "How I communicate",
    "Honors 394",
    "Honors 100",
    "“He said, she said”",
    "Having “ideas that are lying around”",
    "Harassment",
    "Good content",
    "ENGL 131",
    "Durable link",
    "Digital preservation",
    "CSE 390 (for CSE 143)",
    "CSE 390 (for CSE 142)",
    "CSE 190",
    "CSE 142",
    "Content licensing",
    "Content availability",
    "Cause prioritization",
    "Bash shortcuts",
    "Bash aliases",
    "Autumn 2014 at the University of Washington",
    "Anecdote (story)",
    "Working efficiently",
    "The spider",
    "The Red Leech",
    "Setting up a website",
    "An internal monologue",
]

for s in TITLES:
    assert slug(s) == f_slug(s), "ERR: " + s+ slug(s)+ f_slug(s)
    assert f_slug(s) == u_slug(s), "ERR: " + s
